version: '3.7'

services:
  web:
    container_name: forum_web
    build:
      context: .
      dockerfile: dockerfile.prod
    volumes:
      - static_volume:/home/forum/web/static
      - media_volume:/home/forum/web/media
    command: gunicorn forum.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    container_name: forum_db
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - media_volume:/home/forum/web/media
    env_file:
      - ./.env.prod.db

  nginx:
    build: ngnix/
    volumes:
      - static_volume:/home/forum/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
