version: '3.7'

services:
  db:
    container_name: forum_db
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=forum

  web:
    container_name: forum_web
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/forum
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
